version: '3.8'

services:
  postgres:
    image: postgres:17  # Replace '15' with the newest LTS version if updated
    container_name: postgres_sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_air
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
